### ISSUE TITLE
Sudoku Solver

### ISSUE THREAD

**Issue by warmachine028** [HowkMii/ProgrammingProblem#1]
Hi ! I want to add a sudoku solver in python using backtracking . Could you assign me this issue under hacktoberfest2021 so that I can contribute to this project :)

**Comment by HowkMii** [comment]
sure why not?

**Comment by warmachine028** [comment]
> sure why not?
@HowkMii I have successfully added Sudoku Solver using Backtracking Algorithm in python, could you merge my PR :). This is my PR #4
